remote_theme: pages-themes/minimal@v0.2.0
title: progintro @ dit
logo: /assets/img/logo.jpg
description: 
plugins:
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  parse_block_html: true
  toc_levels: 2..2
  input: GFM
  math_engine: mathjax
